openapi: 3.0.3
info:
  title: WannaWork API
  description: API for connecting students with employers for job opportunities
  version: 1.0.0
  contact:
    name: WannaWork Support

servers:
  - url: http://localhost:8080/api/v1
    description: Development server


paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the current status of the API
      responses:
        '200':
          description: API is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
                  message:
                    type: string
                    example: WannaWork API is running

  /login:
    post:
      summary: User login
      description: Authenticate a student or employer and receive a JWT token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: student@example.com
                password:
                  type: string
                  example: securePassword123!
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Autenticazione riuscita
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                  email:
                    type: string
                    example: student@example.com
                  id:
                    type: string
                    example: 507f1f77bcf86cd799439011
                  userType:
                    type: string
                    enum: [Student, Employer]
                    example: Student
                  self:
                    type: string
                    example: api/v1/507f1f77bcf86cd799439011
        '400':
          description: Missing credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /students/registration:
    post:
      summary: Register a new student
      description: Create a new student account with email verification
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - surname
                - email
                - education
                - educationYear
                - password
              properties:
                name:
                  type: string
                  example: Mario
                surname:
                  type: string
                  example: Rossi
                email:
                  type: string
                  example: mario.rossi@example.com
                education:
                  type: string
                  description: MongoDB ObjectId of the education institution
                  example: 507f1f77bcf86cd799439011
                educationYear:
                  type: integer
                  example: 3
                password:
                  type: string
                  example: SecurePass123!
      responses:
        '201':
          description: Registration successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Registrazione avvenuta con successo
                  redirect_url:
                    type: string
                    example: /login
        '400':
          description: Invalid data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Email already registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /employees/registration:
    post:
      summary: Register a new employer
      description: Create a new employer account with email verification
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - companyName
                - email
                - password
                - headquarters
              properties:
                companyName:
                  type: string
                  example: TechCorp S.r.l.
                email:
                  type: string
                  example: hr@techcorp.com
                password:
                  type: string
                  example: SecurePass123!
                headquarters:
                  type: string
                  example: Via Roma 123, 20100 Milano, Italy
                website:
                  type: string
                  example: https://www.techcorp.com
      responses:
        '201':
          description: Registration successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Registrazione avvenuta con successo
                  redirect_url:
                    type: string
                    example: /login
        '400':
          description: Invalid data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Company already registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /skills:
    get:
      summary: Get all skills
      description: Retrieve a list of all available skills sorted alphabetically
      responses:
        '200':
          description: List of skills retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  count:
                    type: integer
                    example: 25
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          example: 507f1f77bcf86cd799439011
                        name:
                          type: string
                          example: JavaScript
                        type:
                          type: string
                          example: Programming Language
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /educations:
    get:
      summary: Get all educational institutions
      description: Retrieve a list of all educational institutions sorted alphabetically
      responses:
        '200':
          description: List of educational institutions retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  count:
                    type: integer
                    example: 15
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          example: 507f1f77bcf86cd799439011
                        name:
                          type: string
                          example: Università degli Studi di Trento
                        university:
                          type: boolean
                          example: true
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /verify-email:
    get:
      summary: Verify email address
      description: Verify a user's email address using the token sent via email
      parameters:
        - in: query
          name: token
          schema:
            type: string
          description: JWT token sent to the user's email
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
      responses:
        '200':
          description: Email verified successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Email verificata con successo!
        '400':
          description: Invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Student:
      type: object
      required:
        - name
        - surname
        - email
        - education
        - educationYear
        - password
      properties:
        _id:
          type: string
          example: 507f1f77bcf86cd799439011
        name:
          type: string
          example: Mario
        surname:
          type: string
          example: Rossi
        email:
          type: string
          example: mario.rossi@example.com
        education:
          type: string
          description: Reference to Education document
          example: 507f1f77bcf86cd799439011
        educationYear:
          type: integer
          example: 3
        isVerified:
          type: boolean
          default: false
          example: false
        createdAt:
          type: string
        updatedAt:
          type: string

    Employer:
      type: object
      required:
        - companyName
        - email
        - password
        - headquarters
      properties:
        _id:
          type: string
          example: 507f1f77bcf86cd799439011
        companyName:
          type: string
          example: TechCorp S.r.l.
        email:
          type: string
          example: hr@techcorp.com
        headquarters:
          type: string
          example: Via Roma 123, 20100 Milano, Italy
        website:
          type: string
          example: https://www.techcorp.com
        isVerified:
          type: boolean
          default: false
          example: false
        createdAt:
          type: string
        updatedAt:
          type: string

    Skill:
      type: object
      required:
        - name
        - type
      properties:
        _id:
          type: string
          example: 507f1f77bcf86cd799439011
        name:
          type: string
          example: JavaScript
        type:
          type: string
          example: Programming Language
        description:
          type: string
          example: A versatile programming language for web development
        createdAt:
          type: string
        updatedAt:
          type: string

    Education:
      type: object
      required:
        - name
      properties:
        _id:
          type: string
          example: 507f1f77bcf86cd799439011
        name:
          type: string
          example: Università degli Studi di Trento
        university:
          type: boolean
          default: false
          example: true
        createdAt:
          type: string
        updatedAt:
          type: string

    AvailabilityProfile:
      type: object
      required:
        - student
        - skills
      properties:
        _id:
          type: string
          example: 507f1f77bcf86cd799439011
        student:
          type: string
          description: Reference to Student document
          example: 507f1f77bcf86cd799439011
        phone:
          type: string
          example: '+39 123 456 7890'
        skills:
          type: array
          items:
            type: string
          example: ['507f1f77bcf86cd799439011', '507f1f77bcf86cd799439012']
        experience:
          type: array
          items:
            type: string
          example: ['Junior Developer at XYZ Corp']
        workHours:
          type: number
          example: 20
        availability:
          type: string
        cvFile:
          type: object
          properties:
            filename:
              type: string
            mimeType:
              type: string
              default: application/pdf
            size:
              type: number
            path:
              type: string
        createdAt:
          type: string
        updatedAt:
          type: string

    Offer:
      type: object
      required:
        - employee
        - position
        - description
        - workHours
        - workLocation
        - contacts
      properties:
        _id:
          type: string
          example: 507f1f77bcf86cd799439011
        employee:
          type: string
          description: Reference to Employer document
          example: 507f1f77bcf86cd799439011
        position:
          type: string
          example: Junior Web Developer
        description:
          type: string
          example: Looking for a motivated junior developer to join our team
        requirements:
          type: array
          items:
            type: string
          example: ['JavaScript', 'React', 'Node.js']
        workHours:
          type: number
          example: 40
        contractExpiration:
          type: string
        workLocation:
          type: string
          example: Milano, Italy
        contacts:
          type: array
          items:
            type: string
          example: ['hr@techcorp.com', '+39 02 1234567']
        createdAt:
          type: string
        updatedAt:
          type: string

    Application:
      type: object
      required:
        - student
        - date
      properties:
        _id:
          type: string
          example: 507f1f77bcf86cd799439011
        student:
          type: string
          description: Reference to Student document
          example: 507f1f77bcf86cd799439011
        offer:
          type: string
          description: Reference to Offer document (note that schema has duplicate 'student' field, assuming second should be 'offer')
          example: 507f1f77bcf86cd799439012
        date:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string

    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: Errore durante l'operazione
        error:
          type: string
          example: Dettaglio tecnico dell'errore

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: JWT token obtained from the /login endpoint

security:
  - bearerAuth: []